const stateMap = { trend_continuation:'趋势延续', short_squeeze_risk:'逼空风险', long_liquidation_risk:'多头清算风险', overheated:'过热拥挤', chop_no_trade:'震荡/不交易' };
const actionMap = { trend_continuation:'顺势看，等回踩确认，不追极端拉升。', short_squeeze_risk:'向上加速风险高，别逆势空。', long_liquidation_risk:'小心下破连锁清算，不急着抄底。', overheated:'拥挤过热，减仓/不追高优先。', chop_no_trade:'没有明显 edge，少动或者不交易。' };
const SYM = { BTCUSDT:{okx:'BTC-USDT',cg:'bitcoin'}, ETHUSDT:{okx:'ETH-USDT',cg:'ethereum'}, SOLUSDT:{okx:'SOL-USDT',cg:'solana'} };
let mainChart, candleSeries, oiChart, oiSeries, fundingChart, fundingSeries, tradeSocket; let buyVol = 0, sellVol = 0; const debugLines = [];
function dbg(msg){ const line=`[${new Date().toLocaleTimeString()}] ${msg}`; debugLines.unshift(line); if(debugLines.length>40) debugLines.pop(); const el=document.getElementById('debugPanel'); if(el) el.textContent=debugLines.join('\n'); const s=document.getElementById('debugSummary'); if(s) s.textContent=msg; console.log(msg); }
window.addEventListener('error', e => dbg(`window error: ${e.message}`));
window.addEventListener('unhandledrejection', e => dbg(`promise error: ${e.reason}`));
function fmtNum(v, digits = 2) { if (v === null || v === undefined || Number.isNaN(v)) return '-'; return Number(v).toLocaleString(undefined, { maximumFractionDigits: digits, minimumFractionDigits: digits }); }
function setBadge(risk) { const el = document.getElementById('statusBadge'); el.textContent = risk || 'UNKNOWN'; el.className = 'badge ' + (risk === 'LOW' ? 'good' : risk === 'MEDIUM' ? 'warn' : risk === 'HIGH' ? 'bad' : 'neutral'); }
function setText(id, text){ const el=document.getElementById(id); if(el) el.textContent=text; }
function currentSymbol(){ return document.getElementById('symbolSelect').value; }
function currentInterval(){ return document.getElementById('intervalSelect').value; }
function currentOkx(){ return SYM[currentSymbol()].okx; }
function currentCg(){ return SYM[currentSymbol()].cg; }
async function j(url){ dbg(`fetch ${url}`); const r = await fetch(url); if(!r.ok) throw new Error(`${r.status} ${url}`); return r.json(); }
function initCharts(){ if(!window.LightweightCharts){ dbg('lightweight charts missing'); return; } const common={layout:{background:{color:'#0f162a'},textColor:'#dbe7ff'},grid:{vertLines:{color:'#18223d'},horzLines:{color:'#18223d'}},rightPriceScale:{borderColor:'#243255'},timeScale:{borderColor:'#243255'}}; mainChart=LightweightCharts.createChart(document.getElementById('chart'),{...common,height:360}); candleSeries=mainChart.addCandlestickSeries({upColor:'#22c55e',downColor:'#ef4444',borderVisible:false,wickUpColor:'#22c55e',wickDownColor:'#ef4444'}); oiChart=LightweightCharts.createChart(document.getElementById('oiChart'),{...common,height:225}); oiSeries=oiChart.addLineSeries({color:'#60a5fa',lineWidth:2}); fundingChart=LightweightCharts.createChart(document.getElementById('fundingChart'),{...common,height:225}); fundingSeries=fundingChart.addHistogramSeries({color:'#f59e0b'}); dbg('charts initialized'); }
async function loadCandles(){ try { const barMap={ '1m':'1m','5m':'5m','15m':'15m','1h':'1H' }; const data=await j(`https://www.okx.com/api/v5/market/candles?instId=${encodeURIComponent(currentOkx())}&bar=${barMap[currentInterval()]}&limit=300`); const rows=(data.data||[]).slice().reverse(); const candles=rows.map(x=>({ time: Math.floor(Number(x[0])/1000), open:Number(x[1]), high:Number(x[2]), low:Number(x[3]), close:Number(x[4]) })); if(candleSeries) candleSeries.setData(candles); const last=candles[candles.length-1]; setText('priceLine',`${currentSymbol()} | ${currentInterval()} | src:okx-browser | candles:${candles.length} | last:${last?fmtNum(last.close,2):'-'}`); dbg(`candles loaded: ${candles.length}`); } catch(e){ dbg(`candles failed: ${e.message}`); setText('priceLine',`candles failed: ${e.message}`); } }
function pushTradeRow(price, qty, side, ts){ const tape=document.getElementById('tradeTape'); if(!tape) return; const row=document.createElement('div'); row.className='trade-row'; row.innerHTML=`<span>${new Date(ts).toLocaleTimeString()}</span><span class="${side}">${price}</span><span class="${side}">${qty}</span>`; tape.prepend(row); while(tape.children.length>120)tape.removeChild(tape.lastChild); }
function connectTrades(){ try { if(tradeSocket) tradeSocket.close(); buyVol=0; sellVol=0; tradeSocket=new WebSocket('wss://ws.okx.com:8443/ws/v5/public'); tradeSocket.onopen=()=>{ dbg(`ws open for ${currentOkx()}`); tradeSocket.send(JSON.stringify({op:'subscribe',args:[{channel:'trades',instId:currentOkx()}]})); }; tradeSocket.onerror=()=>dbg('ws error'); tradeSocket.onclose=()=>dbg('ws closed'); tradeSocket.onmessage=(ev)=>{ const msg=JSON.parse(ev.data); (msg.data||[]).forEach(d=>{ const price=Number(d.px).toFixed(2); const qty=Number(d.sz).toFixed(4); const side=d.side==='buy'?'buy':'sell'; if(side==='buy') buyVol+=Number(d.sz); else sellVol+=Number(d.sz); pushTradeRow(price,qty,side,Number(d.ts)); }); setText('tapeStats',`buyVol:${buyVol.toFixed(2)} | sellVol:${sellVol.toFixed(2)} | imbalance:${(buyVol-sellVol).toFixed(2)} | src:okx-ws`); }; } catch(e){ dbg(`ws setup failed: ${e.message}`); } }
async function loadDepth(){ try { const data=await j(`https://www.okx.com/api/v5/market/books?instId=${encodeURIComponent(currentOkx())}&sz=20`); const book=(data.data||[{}])[0]; const bids=(book.bids||[]).map(x=>({price:Number(x[0]),qty:Number(x[1]),notional:Number(x[0])*Number(x[1])})); const asks=(book.asks||[]).map(x=>({price:Number(x[0]),qty:Number(x[1]),notional:Number(x[0])*Number(x[1])})); const bidsEl=document.getElementById('bidsBook'); const asksEl=document.getElementById('asksBook'); if(bidsEl) bidsEl.innerHTML=''; if(asksEl) asksEl.innerHTML=''; bids.forEach(x=>{ const row=document.createElement('div'); row.className='book-row buy'; row.innerHTML=`<span>${fmtNum(x.price,2)}</span><span>${fmtNum(x.qty,4)} / ${fmtNum(x.notional,0)}</span>`; bidsEl.appendChild(row);}); asks.forEach(x=>{ const row=document.createElement('div'); row.className='book-row sell'; row.innerHTML=`<span>${fmtNum(x.price,2)}</span><span>${fmtNum(x.qty,4)} / ${fmtNum(x.notional,0)}</span>`; asksEl.appendChild(row);}); const bidSum=bids.reduce((a,b)=>a+b.qty,0), askSum=asks.reduce((a,b)=>a+b.qty,0), bidNotional=bids.reduce((a,b)=>a+b.notional,0), askNotional=asks.reduce((a,b)=>a+b.notional,0); setText('depthStats',`src:okx-browser | bidQty:${fmtNum(bidSum,2)} | askQty:${fmtNum(askSum,2)} | bid$:${fmtNum(bidNotional,0)} | ask$:${fmtNum(askNotional,0)} | imbalance:${fmtNum(bidSum-askSum,2)}`); dbg('depth loaded'); } catch(e){ dbg(`depth failed: ${e.message}`); setText('depthStats',`depth failed: ${e.message}`); } }
async function loadMarket(){ try { const [ticker, trades, cg] = await Promise.all([ j(`https://www.okx.com/api/v5/market/ticker?instId=${encodeURIComponent(currentOkx())}`), j(`https://www.okx.com/api/v5/market/trades?instId=${encodeURIComponent(currentOkx())}&limit=100`), j(`https://api.coingecko.com/api/v3/coins/${encodeURIComponent(currentCg())}`) ]); const t=(ticker.data||[{}])[0]; const rows=trades.data||[]; const takerBuy=rows.filter(x=>x.side==='buy').reduce((a,b)=>a+Number(b.sz),0); const takerSell=rows.filter(x=>x.side==='sell').reduce((a,b)=>a+Number(b.sz),0); const md=cg.market_data||{}; const open24=Number(t.open24h||0), last=Number(t.last||0); setText('marketTimestamp',`${currentSymbol()} | okx+cg browser`); setText('marketVolume','$'+fmtNum(md.total_volume?.usd,0)); setText('marketCap','$'+fmtNum(md.market_cap?.usd,0)); setText('marketHigh','$'+fmtNum(Number(t.high24h||0),2)); setText('marketLow','$'+fmtNum(Number(t.low24h||0),2)); setText('marketChange',open24?fmtNum((last/open24-1)*100,2)+'%':'-'); setText('weightedAvg','-'); setText('quoteVolume','$'+fmtNum(Number(t.volCcy24h||0),0)); setText('tradeCount',fmtNum(rows.length,0)); setText('takerBuy',fmtNum(takerBuy,2)); setText('takerSell',fmtNum(takerSell,2)); const td=document.getElementById('takerDelta'); if(td){ td.textContent=fmtNum(takerBuy-takerSell,2); td.className = Number(takerBuy-takerSell) >= 0 ? 'up' : 'down'; } dbg('market loaded'); } catch(e){ dbg(`market failed: ${e.message}`); setText('marketTimestamp',`market failed: ${e.message}`); } }
async function loadState(){ try { const [snapRes, reportRes]=await Promise.all([fetch('/api/snapshot'), fetch('/api/report')]); const data=await snapRes.json(); const report=await reportRes.text(); const s=data.snapshot, v=data.verdict; setText('stateName',stateMap[v.state]||v.state); setText('actionBias',actionMap[v.state]||'-'); setText('riskLevel',v.risk); setText('confidence',v.confidence); setText('timestamp',new Date(s.ts*1000).toLocaleString()); setText('price','$'+fmtNum(s.price,2)); setText('oi',fmtNum(s.oi,0)); setText('funding',fmtNum(s.funding,4)+'%'); setText('longLiq','$'+fmtNum(s.long_liq_24h,0)); setText('shortLiq','$'+fmtNum(s.short_liq_24h,0)); setText('sources',`liq:${data.liquidation_source} | oi:${data.oi_source} | funding:${data.funding_source}`); const sm=document.getElementById('structureMetrics'); if(sm) sm.innerHTML=''; Object.entries(v.metrics).forEach(([k,val])=>{ const div=document.createElement('div'); div.className='metric'; const cls=typeof val==='number'&&val<0?'down':'up'; div.innerHTML=`<span>${k}</span><strong class="${cls}">${val}</strong>`; sm.appendChild(div); }); const tags=document.getElementById('tags'); if(tags) tags.innerHTML=''; (v.tags||[]).forEach(tag=>{ const span=document.createElement('span'); span.className='tag'; span.textContent=tag; tags.appendChild(span); }); if((!v.tags||!v.tags.length) && tags){ const span=document.createElement('span'); span.className='tag'; span.textContent='none'; tags.appendChild(span); } setText('rawReport',report); setBadge(v.risk); if(oiSeries) oiSeries.setData((s.history_oi||[]).map((x,i)=>({time:i+1,value:x}))); if(fundingSeries) fundingSeries.setData((s.history_funding||[]).map((x,i)=>({time:i+1,value:x,color:x>=0?'#22c55e':'#ef4444'}))); setText('curveStats',`funding:${fmtNum(s.funding,4)}% | oi:${fmtNum(s.oi,0)}`); dbg('state loaded'); } catch(e){ dbg(`state failed: ${e.message}`); setText('rawReport',`state failed: ${e.message}`); setBadge('ERROR'); } }
async function refreshAll(){ dbg('manual refresh'); await fetch('/api/refresh',{method:'POST'}).catch(e=>dbg(`refresh api failed: ${e.message}`)); await Promise.allSettled([loadState(),loadCandles(),loadDepth(),loadMarket()]); }
function hardReloadFeeds(){ dbg(`reload feeds ${currentSymbol()} ${currentInterval()}`); connectTrades(); loadCandles(); loadDepth(); loadMarket(); }
document.getElementById('refreshBtn').addEventListener('click', refreshAll); document.getElementById('intervalSelect').addEventListener('change', ()=>loadCandles()); document.getElementById('symbolSelect').addEventListener('change', hardReloadFeeds); dbg('boot start'); initCharts(); Promise.allSettled([loadState(),loadCandles(),loadDepth(),loadMarket()]).then(()=>{ dbg('initial load settled'); connectTrades(); }); setInterval(()=>loadDepth(), 5000); setInterval(()=>loadMarket(), 30000);
